// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT9jHZgj2jUp488npcKPd4ZiLXwsBTLso',
    appId: '1:828274707706:android:af0ad5db9d7487967acd43',
    messagingSenderId: '828274707706',
    projectId: 'netfilxclone-94f6d',
    storageBucket: 'netfilxclone-94f6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmpSpCsKUzk2ua5ktKwP8n9h2s9jatbO0',
    appId: '1:828274707706:ios:aa5989453dc406597acd43',
    messagingSenderId: '828274707706',
    projectId: 'netfilxclone-94f6d',
    storageBucket: 'netfilxclone-94f6d.appspot.com',
    iosBundleId: 'com.example.netflixProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmpSpCsKUzk2ua5ktKwP8n9h2s9jatbO0',
    appId: '1:828274707706:ios:4c42f7ac9356b9667acd43',
    messagingSenderId: '828274707706',
    projectId: 'netfilxclone-94f6d',
    storageBucket: 'netfilxclone-94f6d.appspot.com',
    iosBundleId: 'com.example.netflixProvider.RunnerTests',
  );
}
